#!/usr/bin/env ruby

require 'set'

MAX_KEY = 0xffffff
SIZE = 1_000_000

class Generator

  CHARS = [?a..?z, ?A..?Z, ?0..?9, %W[_ -]].map(&:to_a).flatten

  class << self
    def generate_string length=6, collision_rate=3
      if @str_list && (rand(100) < collision_rate)
        @str_list.sample
      else
        length = rand(length) if length.is_a? Range

        res = length.times.with_object("") do |_, res|
          res << CHARS.sample
        end
        @str_list ||= []
        @str_list << res

        res
      end
    end

    def generate_number range = 0..10_000
      rand(range)
    end
  end
end

class Entry < Struct.new(:key, :string, :number)

  def initialize
    self.key = rand(1...MAX_KEY)
    self.string = Generator.generate_string 10..12
    self.number = Generator.generate_number 0..800_000
  end

  def hash
    self.key.hash
  end

  def ==(other)
    self.string == other.string && self.number == other.number or
      self.key == other.key
  end

  def to_s
     '%0.6x %d %s' % [key, number, string]
  end
end

elems = loop.with_object(Array.new) do |_, array|
  break array if array.size >= SIZE * 1.1
  array << Entry.new
end

# $stderr.puts elems.size.to_s

elems.uniq! { |el| "#{el.string} #{el.number}" }
# $stderr.puts elems.size.to_s

elems.uniq! { |el| el.key}
# $stderr.puts elems.size.to_s

elems = elems.first SIZE

elems = loop.with_object(elems) do |_, array|
  break array if array.size >= SIZE
  candidate = Entry.new
  array << candidate  if array.none? { |el| el == candidate }
end

$stderr.puts("Total: #{elems.size}")
$stderr.puts("String field collisions: " +
             (elems.size - elems.group_by(&:string).keys.size).to_s)
$stderr.puts("Numeric field collisions: " +
             (elems.size - elems.group_by(&:number).keys.size).to_s)

puts elems.map(&:to_s).join(?\n)
