#!/usr/bin/env ruby

include Process

def spawn_process
  spawn(File.join(Dir.pwd, "../core/hash"), @p_sizes.pop.to_s, :chdir => File.join(Dir.pwd, "../results"))
  @children_count += 1
  print '.'
end

@p_sizes = [20]
@p_sizes += [20, 200, 2000, 20000].map{ |i| (i..(i * 10)).step(i).to_a[1..-1] }.flatten
@p_sizes.reverse!
@children_count = 0

4.times{ spawn_process }
while ( wait && @p_sizes.any? ) do
  spawn_process
end

begin
  4.times{ wait }
rescue
end
