#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), 'digsig.rb')

def wrong_usage
  STDERR.puts "Wrong arguments.\nUsage: ./digsig [--sign/--check] [r=<r>, ko=<ko>] filename"
  exit
end

if ARGV[0] == '--sign'
  RSA_DigitalSignature.sign_file ARGV[1]
elsif ARGV[0] == '--check'
  params_hash = Hash[ *ARGV[2..-1].join.split(?,).map{ |el| [el.split(?=)[0], el.split(?=)[1]] }.flatten ]
  wrong_usage unless params_hash.has_key?('r') && params_hash.has_key?('ko')
  r = params_hash['r'].to_i; ko = params_hash['ko'].to_i;
  RSA_DigitalSignature.check_signature ARGV[1], ko, r
else
  wrong_usage
end
