#!/usr/bin/env ruby

require 'json'

unless File.exists?('./jquery.min.js')
  `wget http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js -O jquery.min.js`
end

html_filename = ARGV[1] || "out.html"
html = File.open(html_filename, 'w')

html << <<EOH
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css" media="screen">
      .closed > div {
        display: none;
      }
      .hidder {
        min-height: 10px;
        background-color: #CFF;
        z-index: 1;
      }
      .hidder > .hidder {
        background-color: #AEE;
        z-index: 2;
      }
      .hidder > .hidder > .hidder {
        background-color: #8DD;
        z-index: 3;
      }
      .it {
        background-color: #DDA;
      }
      .hidder > div {
        margin: 2px 10px;
      }
      p {
        margin: 0;
      }
    </style>
    <script type="text/javascript"
            src="jquery.min.js"></script>
    <script type="text/javascript">
      $(document).delegate('.hidder', 'click', function(e) {
        e.stopPropagation();
        if ($(this).hasClass('closed'))
          $(this).removeClass('closed');
        else
          $(this).addClass('closed');
      });
    </script>
  </head>
  <body>
    <div class="json">
      <div class="hidder">
        Area conteiner:
EOH

json = JSON.load(File.read(ARGV[0] || "out.json"))

html << "(areas: #{json['areas'].size})"

json['areas'].each do |area|
  html << '<div class="hidder closed">'
  html << 'Area: (max_key: ' + area['maxKey'].inspect + ", "
  html << 'interspaces: ' + area['interspaces'].size.to_s + ")\n"
  area['interspaces'].each do |interspace|
    html << '<div class="hidder closed">'
    html << 'Interspace: (max_key: ' + interspace['maxKey'].inspect + ", "
    html << 'items: ' + interspace['items'].size.to_s + ")\n"
    interspace['items'].each do |item|
      html << '<div class="it">'
      html << "<p>field: #{item['field']} </p>\n"
      html << "<p>key:   #{item['key']}   </p>\n"
      html << '</div>'
    end
    html << '</div>'
  end
  html << '</div>'
end


html << <<EOH
      </div>
    </div>
  </body>
</html>
EOH

html.close

`#{ARGV[2]} #{html_filename} &` if ARGV[2]
